myapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView

urlpatterns = [
    path("", views.index, name="home"),
    path("about/", views.about, name="about"),
    path("contacts/", views.contacts, name="contacts"),
    path("barbers/", views.barbers, name="barbers"),
    path("services/", views.services, name="services"),
    path("login/", views.loginpage, name="loginpage"),
    path("loginhandle/", views.loginhandle, name="loginhandle"),
    path("signup/", views.signup, name="signup"),
    path("signuphandle/", views.signuphandle, name="signuphandle"),
    path("otppage/", views.otppage, name="otppage"),
    path("otppage2/", views.otppage2, name="otppage2"),
    path("otpvalidate/", views.otpvalidate, name="otpvalidate"),
    path("resetpassvalidate/", views.resetpassvalidate, name="resetpassvalidate"),
    path("resetpass1/", views.resetpass1, name="resetpass1"),
    path("resetpass2/", views.resetpass2, name="resetpass2"),
    path("logout/", views.logoutpage, name="logoutpage"),
]

salon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404


urlpatterns = [
    path("admin1/", admin.site.urls),
    path("", include("myapp.urls")),
    path("a/", include("appointment.urls")),
    path("s/", include("shop.urls")),
    path("admin/", include("admin.urls")),
    path("customer/", include("customer.urls")),
    path("employee/", include("employee.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "myapp.views.custom_404_view"

shop/urls.py
from django.urls import path
from . import views

app_name = 'myapp_shop'

urlpatterns = [
    path('addcart/<int:pid>/', views.addcart, name="addcart"),
    path('addcartplus/<int:pid>/', views.addcartplus, name="addcartplus"),
    path('removecartminus/<int:pid>/', views.removecartminus, name="removecartminus"),
    path('removecart/<int:pid>/', views.removecart, name="removecart"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('bookorder/', views.bookorder, name="bookorder"),
    path('finish/', views.finish, name="finish"),
    path('shop/', views.shop, name="shop"),
    path('single-product/<int:pid>/', views.single_prod, name="single_prod")
]

myapp/models.py
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser,PermissionsMixin  
from django.db import models
from .manager import UserManager
import os

# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=50)

# ALTER TABLE myapp_user DROP INDEX username
class User(AbstractUser,PermissionsMixin):
    id = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(('first name'), max_length=30, blank=True)
    last_name = models.CharField(('last name'), max_length=30, blank=True)
    phone = models.CharField(max_length=20,default='')
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True) 
    
    is_staff = models.BooleanField(default=False)  
    is_active = models.BooleanField(default=True) 
    is_employee = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    # class Meta(AbstractUser.Meta):
    #     swappable = 'AUTH_USER_MODEL'
        
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    
    gender = models.CharField(max_length=1,choices=GENDER_CHOICES,default='') 
    uimg = models.ImageField(upload_to="user/images",default="") 
     
    def __str__(self):
        return self.email
    
    def delete(self, *args, **kwargs):
        # delete the file from the file system
        if self.uimg:
            os.remove(self.uimg.path)

        # call the parent class delete method to delete the object
        super(User, self).delete(*args, **kwargs)

class OTP(models.Model):
    email = models.EmailField(max_length=254,default=" ")
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)   
    otp = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)


# class Customer1(models.Model):
#     user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)

       
class Admin(models.Model):
    aid = models.AutoField(primary_key=True)
    aname = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    password = models.CharField(max_length=50)
    contactno = models.CharField(max_length=10)
    
    def __str__(self):  
        return self.aname
    
    

myapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm  
from django.db.models import fields  
from django import forms  
from .models import User
from django.contrib.auth import get_user_model  
  
User = get_user_model()  
  
class CustomUserCreationForm(UserCreationForm):  
  
    password1 = forms.CharField(widget=forms.PasswordInput)  
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)  
    first_name = forms.CharField(label="First Name",widget=forms.TextInput)
    last_name = forms.CharField(label="Last Name",widget=forms.TextInput)
    phone = forms.CharField(label="Phone No",widget=forms.TextInput,max_length=20)
      
    class Meta:  
        model = User  
        fields = ('email', )  
      
    def clean_email(self):  
        email = self.cleaned_data.get('email')  
        qs = User.objects.filter(email=email)  
        if qs.exists():  
            raise forms.ValidationError("Email is taken")  
        return email  
  
    def clean(self):  
        '''  
        Verify both passwords match.  
        '''  
        cleaned_data = super().clean()  
        password1 = cleaned_data.get("password1")  
        password2 = cleaned_data.get("password2")  
          
        if password1 is not None and password1 != password2:  
            self.add_error("password2", "Your passwords must match")  
        return cleaned_data  
  
    def save(self, commit=True):  
        # Save the provided password in hashed format  
        user = super().save(commit=False)  
        user.set_password(self.cleaned_data["password1"])  
        if commit:  
            user.save()  
        return user          
      
  
# class CustomUserChangeForm(UserChangeForm):  
#     class Meta:  
#         model = User  
#         fields = ('email', )  
  
#     def clean_password(self):  
#         # Regardless of what the user provides, return the initial value.  
#         # This is done here, rather than on the field, because the  
#         # field does not have access to the initial value  
#         return self.initial["password1"] 

myapp/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from employee.models import User_Employee
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.utils import timezone
from django.core.mail import send_mail
import pyotp
from django.contrib.auth.decorators import login_required
from appointment.models import Service
from django.contrib.auth.views import PasswordResetView
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.templatetags.static import static


from myapp.models import OTP


def custom_404_view(request, exception):
    return render(request, "myapp/404-page.html", status=404)


# Create your views here.
User = get_user_model()
# ---------email-------------------------------

# --------------------------------------------------


def index(request):
    data = {}
    barbar = User_Employee.objects.all()[:3]
    data["barbar"] = barbar
    if request.user.is_authenticated:
        data["user"] = request.user

    return render(request, "myapp/index.html", data)


def logoutpage(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Logged out successfully!")
        return redirect("home")
    else:
        return redirect("home")


def loginhandle(request):
    data = {}

    if request.method == "POST":
        loginemail = request.POST.get("loginemail", "")
        loginpassword = request.POST.get("loginpass", "")
        user = authenticate(email=loginemail, password=loginpassword)

        print(loginemail)
        print(loginpassword)

        if user is not None:
            login(request, user)
            username = request.user.first_name
            mymsg = "Successfully Logged In " + username
            messages.success(request, mymsg)
            request.session["user_id"] = user.id
            if request.user.is_customer:
                return redirect("home")
            elif request.user.is_employee:
                return redirect("edashboard")
            elif request.user.is_admin:
                return redirect("dashboard")

        else:
            messages.error(request, "Invalid Email address or Password !")
            # return redirect("loginpage")
            data = {}
            data["loginemail"] = loginemail
            data["loginpass"] = loginpassword
            return render(request, "myapp/login.html", data)

    return HttpResponse("404- Not found")
    # return HttpResponse("login")
    # return redirect('home')
    # return render(request,"/myapp/index.html")


def signuphandle(request):
    if request.method == "POST":
        fname = request.POST.get("fname", "")
        lname = request.POST.get("lname", "")
        email = request.POST.get("email", "")
        pass1 = request.POST.get("pass1", "")
        pass2 = request.POST.get("pass2", "")

        if pass1 == pass2:
            try:
                user = User.objects.filter(email=email).first()

                if user:
                    messages.error(
                        request,
                        "Email ID User Already associated with an account Please Use Different Email Id ",
                    )
                    data["fname"] = fname
                    data["lname"] = lname
                    data["pass1"] = pass1
                    data["pass2"] = pass2
                    # return redirect("/signup/")
                    return render(request, "myapp/signup.html", data)

                else:
                    subject = "OTP Verification For Complate Registration"
                    message = "Your Otp Is "
                    otp = generate_otp(email, subject, message)
                    print("otp : ", otp)
                    request.session["signup_data"] = {
                        "email": email,
                        "fname": fname,
                        "lname": lname,
                        "password": pass1,
                        "otp": otp,
                    }
                    return redirect("/otppage/")
            except Exception as e:
                messages.error(request, e)
                return redirect("/signup/")
        else:
            msg = "Password and Confirm Password did not match"
            messages.error(request, msg)
            # return redirect("/signup/")
            data = {}
            data["fname"] = fname
            data["lname"] = lname
            data["email"] = email
            data["pass1"] = pass1
            data["pass2"] = pass2
            return render(request, "myapp/signup.html", data)

    else:
        messages.error(request, "Somthing Wrong")
        return redirect("home")


def otppage(request):
    if "signup_data" in request.session:
        return render(request, "myapp/otppage.html")
    return redirect("home")


def generate_otp(email, subject, message):
    totp = pyotp.TOTP("base32secret3232")
    otp_value = totp.now()
    message = message + otp_value
    send_otp_email(email, subject, message)
    return otp_value


def send_otp_email(email, subject, message):
    # logo_url = request.build_absolute_uri(settings.STATIC_URL + "images/logo.png")
    logo_url = "images/logo-default-dark-200x36.png"
    from_email = settings.DEFAULT_FROM_EMAIL
    recipient_list = [email]
    html_message = render_to_string(
        "email_templates/email.html",
        {"subject": subject, "message": message, "logo_url": logo_url},
    )
    mail = EmailMultiAlternatives(subject, "", from_email, recipient_list)
    mail.attach_alternative(html_message, "text/html")
    mail.send()


def otpvalidate(request):
    if "signup_data" in request.session:
        otp = request.session["signup_data"]["otp"]
        if request.method == "POST":
            i1 = request.POST.get("otpi1", "")
            i2 = request.POST.get("otpi2", "")
            i3 = request.POST.get("otpi3", "")
            i4 = request.POST.get("otpi4", "")
            i5 = request.POST.get("otpi5", "")
            i6 = request.POST.get("otpi6", "")

            reciveotp = i1 + i2 + i3 + i4 + i5 + i6
            try:
                if otp == reciveotp:
                    user = User.objects._create_user(
                        email=request.session["signup_data"]["email"],
                        password=request.session["signup_data"]["password"],
                        first_name=request.session["signup_data"]["fname"],
                        last_name=request.session["signup_data"]["lname"],
                        is_customer=True,
                    )
                    del request.session["signup_data"]
                    messages.success(request, "Otp Validate Successfully signup ")
                    return redirect("loginpage")
                else:
                    messages.error(request, "Otp Not Validate")
                    data = {}
                    data["i1"] = i1
                    data["i2"] = i2
                    data["i3"] = i3
                    data["i4"] = i4
                    data["i5"] = i5
                    data["i6"] = i6
                    return render(request, "myapp/otppage.html", data)
            except Exception as e:
                messages.error(request, e)
                return redirect("home")
        else:
            return redirect("home")
    return redirect("home")


def delete_otp(user):
    pyotp.OTP.objects.filter(user=user).delete()


def about(request):
    data = {}
    barbar = User_Employee.objects.all()[:3]
    data["barbar"] = barbar
    return render(request, "myapp/about.html", data)


def contacts(request):
    return render(request, "myapp/contacts.html")


def barbers(request):
    data = {}
    # barbar = User.objects.filter(is_employee=True)
    barbar = User_Employee.objects.all()
    data["barbar"] = barbar
    return render(request, "myapp/barbers.html", data)


def services(request):
    service = Service.objects.all()
    data = {}
    data["service"] = service
    print("data  : ", data)
    return render(request, "myapp/services.html", data)


def loginpage(request):
    if request.user.is_authenticated:
        if request.user.is_employee:
            return redirect("edashboard")
        if request.user.is_admin:
            return redirect("dashboard")

        return redirect("home")
    else:
        return render(request, "myapp/login.html")


def signup(request):
    if request.user.is_authenticated:
        return redirect("home")
    else:
        return render(request, "myapp/signup.html")


def otppage2(request):
    return render(request, "myapp/otppage2.html")


def otppage2(request):
    if "resetotp" in request.session and "resetemail" in request.session:
        return render(request, "myapp/otppage2.html")
    else:
        return redirect("home")


def resetpass1(request):
    if request.method == "POST":
        email = request.POST.get("email", "")
        try:
            user = User.objects.get(email=email)
            subject = "OTP Verification To Forgot Password"
            message = "Your Otp Is "
            otp = generate_otp(email, subject, message)
            print("otp : ", otp)
            request.session["resetemail"] = email
            request.session["resetotp"] = otp
            return redirect("/otppage2/")

        except User.DoesNotExist:
            messages.error(
                request,
                "Email Id Is Not Registration.",
            )
            data = {}
            data["email"] = email
            return render(request, "myapp/resetpass1.html", data)

        return redirect("/resetpass1/")

    return render(request, "myapp/resetpass1.html")

myapp/templates/shop/cart.html
{% extends 'basespecial.html' %}

{% block title %} Cart {% endblock title %}
{% load static %}

{% block body %}
<body>
  <div class="page">
    <main class="page-content" id="perspective">
      <div class="content-wrapper">
        <div class="page-header page-header-perspective">
          <div class="page-header-left"><a class="brand" href="/"><img src="{% static "images/" %}logo-default-dark-200x36.png" alt="" width="200" height="36"/></a></div>
          <div class="page-header-right">
            <div class="booking-control"><a class="btn btn-xs btn-circle btn-primary" href="/a/step1/">BOOK NOW</a></div>
            <div id="perspective-open-menu" data-custom-toggle=".perspective-menu-toggle" data-custom-toggle-hide-on-blur="true"><span class="perspective-menu-text">Menu</span>
              <button class="perspective-menu-toggle"><span></span></button>
            </div>
          </div>
        </div>

        
        
        <div id="wrapper" >

          <nav aria-label="breadcrumb"  style="margin-left: 10%;">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"> <a href="/"> Home </a> </li>
                <li class="breadcrumb-item active" aria-current="page"> Cart </li>
            </ol>
        </nav>
        <section class="section-xl bg-periglacial-blue">
            
          <div class="shell"><a class="link link-primary link-return" href="/s/shop/">Back</a>

          {% if cart_items %}

       
              <div class="table-custom-responsive table-cart-wrap" >
              <ul id="items">
                  
                </ul> 
              
                <table class="table-cart" >
                  <thead>
                    <tr>
                      <th></th>
                      <th>Item</th>
                      <th>Price</th>
                      <th>Quantity</th>
                      <th>SUBTOTAL</th>
                      <th></th>
                    </tr>
                  </thead>

                  <tbody>

                
                   
              
                    {% for i in cart_items %}


                      <tr>
                        <td><img class="cart-image" src="/media/{{i.product.pimg}}" alt="" width="80" height="82"/>
                        </td>
                        <td>
                          <p class="cart-title"><a href="/s/single-product/{{i.product.pid}}">{{i.product.pname}}</a></p>
                        </td>
                        <td>
                          <p class="cart-price"> &#8377; {{i.product.pprice}}</p>
                         
                      
                        </td>
                    
                        <td>
               
                          <a href="  {% url 'myapp_shop:removecartminus' i.product.pid %}" style=" font-weight: bold; font-size: x-large;">-</a>
                          <p class="cart-price" name="quantity" >{{i.quantity}}</p>
                          <a  href="  {% url 'myapp_shop:addcartplus' i.product.pid %}" style=" font-weight: bold; font-size: x-large;">+</a>
                      
                        </td>
                        <td>
                          <p class="cart-price" >&#8377; {% widthratio i.quantity 1 i.product.pprice %} </p>
                        </td>

                        <td><a class="cart-control" href="{% url 'myapp_shop:removecart' i.product.pid %}" onclick="return confirm('Are you sure you want to remove a cart product {{i.product.pname}} ?');"></a></td>
                      </tr>
                    
                      
                      {% endfor %}

                   
                   
                  </tbody>
                  
                </table>
              </div>
              <div class="table-cart-footer">
                <div class="table-cart-footer-left">
                 
                </div>
                <div class="table-cart-footer-right">
                  <dl class="terms-list-bold">
                    <dt>Total</dt>
                    <dd>&#8377; {{total}}</dd>
                  </dl>
                </div>
              </div>
              <div class="table-cart-action-panel">
                <form  method="post" action="/s/checkout/">
                  {% csrf_token %}
                  <input type="hidden" id="SendTotal" name="SendTotal" value="{{total}}" >

                  <li><button  class="btn btn-circle btn-primary" type="submit">    PROCEED TO CHECKOUT</button> </li>
                </form>  
                
              </div>
           

          
        {% else %}
        <div>
        <img  src="{% static "images/" %}cart_empty.png" alt="" style="display: block; margin:  auto; text-align: center;">
        </div>

    
        {% endif %}

      </div>
    </section>

{% endblock body%}

{% block afterFooter%}
        </div>
    <div id="perspective-content-overlay"></div>
</div>
{%endblock afterFooter%}


{% block  afterNavbar%}
  </main>
</div>
{% endblock afterNavbar%}


{% block endofpage%}
  </body>
{% endblock endofpage%}




{% block js %}
<script>

</script>
{% endblock js%}

myapp/templates/shop/finish.html
{% extends 'basefinish.html' %}

{% block title %}Finish {% endblock title %}
{% load static %}


{% block bodytag %}
<body class="one-screen-page">
  {% endblock bodytag %} 

{% block body %}

        <div id="wrapper">
          <section class="section-xl bg-periglacial-blue one-screen-page-content text-center">
            <div class="shell">
              <h2>Thanks for order</h2>
          
              
              <div class="p text-width-small">
                <p class="big">Your Order is completed ! </p>
              </div><a class="btn btn-sm btn-style-1 btn-primary" href="/">Back to homepage</a>
            </div>
          </section>

       

          {% endblock body %}



          {% block afterFooter%}
        </div>
    <div id="perspective-content-overlay"></div>
</div>
{%endblock afterFooter%}


{% block  afterNavbar%}
  </main>
</div>
{% endblock afterNavbar%}


{% block endofpage%}
  </body>
{% endblock endofpage%}



 

myapp/templates/shop/payment.html
{% extends 'basespecial.html' %}


{% block title %} Payment {% endblock title %}

{% block head %}
<style>
 
</style>
    {% endblock head %} 

{% block body %}


{% load static %}
<button id="rzp-button1">Pay with Razorpay</button>
<form action="/s/finish/" method="POST">{%csrf_token%}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>

var options = {
    "key": "rzp_test_heisFYtHc4xPw1", // Enter the Key ID generated from the Dashboard
    "amount": {{SendTotal}}, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Mannu",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "order_IluGWxBm9U8zJ8", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "https://eneqd3r9zrjok.x.pipedream.net/",
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "gaurav.kumar@example.com",
        "contact": "9000090000"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>


{% endblock body %}

myapp/templates/shop/shop.html
{% extends 'base.html' %}

{% block title %} Shop {% endblock title %}
{% block css %} Shop {% endblock css %}

{% load static %}

{% block bodytag %}
<body>
{% endblock bodytag %}

{% block body %} 

        <div id="wrapper">
          <div class="page-title">
            <div class="page-title-content">
              <div class="shell">
                <p class="page-title-header">Shop </p>
              </div>
            </div>
          </div>


          <div class="shop-panel">
            <div class="shell">
              <div class="shop-panel-inner">
                <div class="shop-panel-left"><a class="shop-panel-link" href="/s/cart/"><span class="icon fa fa-shopping-cart carts"></span> <span class="count" >{{count}}</span></a><span class="shop-panel-price" > </span></div>
                <div class="shop-panel-right">
                  
                                     <div class="shop-panel-select"><span class="shop-panel-select-title">Sort By</span>
                                      {% comment %} <form action="/s/shop/" method="post">
                                        {% csrf_token %} {% endcomment %}
                                   
                                        <select class="form-control select-filter" data-minimum-results-for-search="Infinity" data-custom-theme="modern">
                      <option value="3">Price</option>
                      
                      <option value="4" name="lh">Lowest to Highest</option>
                      <option value="5" name="hl">Highest to Lowest</option>
                    </select>

                  {% comment %} </form> {% endcomment %}
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <section class="section-md bg-periglacial-blue text-center">
            <div class="shell">
             {% if products %}
              <div class="range range-30">
                 
                {% for i in products  %}
                <p>{{i.products}}</p>
              

                <div class="cell-sm-6 cell-md-4" id="product-{{ i.pid }}">
                  <article class="product">
                    <a class="product-image"  href="/s/single-product/{{i.pid}}"><img src="/media/{{i.pimg}}" alt="" width="175" height="168"/></a>
                    <p class="product-title" name="pname" id="pname{{i.pid}}"><a href="/s/single-product/{{i.pid}}">{{i.pname}}</a></p>
                    <p class="product-price"id="price" name="pprice">Rs.{{i.pprice}}
                    </p>
                          
         
                    {% for j in itemcart  %}
                      
                      {% if i.pid == j.product.pid %}
                    
                      <a class="btn-shop addcart" href="/s/cart/">
                        <span class="btn-shop-icon fa fa-shopping-cart "></span>
                        <span class="btn-shop-text " >GO TO CART</span>
                      </a>
                      
                      {% else %}
                     
                      {% if forloop.last %}
                    
                      <a class="btn-shop addcart" href="  {% url 'myapp_shop:addcart' i.pid %}"  >
                        <span class="btn-shop-icon fa fa-shopping-cart "></span>
                        <span class="btn-shop-text " >ADD TO CART</span>
                      </a> 
                    
                      {% endif %}
                   {% endif %} 
                    
                    {% empty %}

                    <a class="btn-shop addcart" href="  {% url 'myapp_shop:addcart' i.pid %}"  >
                      <span class="btn-shop-icon fa fa-shopping-cart "></span>
                      <span class="btn-shop-text " >ADD TO CART</span>
                    </a> 
                  {% endfor %}
              

            

                 
                 

                  </article>

                
                </div> 
                
                 {% endfor %}
                  <!-- </form> -->
              </div>
            
              <ul class="pagination-custom">
                <li class="disabled"><a href="#"></a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li class="ellipsis">...</li>
                <li><a href="#">12</a></li>
                <li><a href="#"></a></li>
              </ul>
             {% else %}
             <h6>No have Any Product Available</h6>
             {% endif %}
            </div>
          </section>
        
        {% endblock body %}

{% block js%}
 
<script>
   
 </script>
{% endblock js %}


{% block afterFooter%}
</div>
<div id="perspective-content-overlay"></div>
</div>
{%endblock afterFooter%}


{% block  afterNavbar%}
</main>
</div>
{% endblock afterNavbar%}


{% block endofpage%}
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</body>
{% endblock endofpage%}